stages:
  - check

check_approval:
  stage: check
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && 
           $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'
  script:
    - |
      echo "=== Проверка статуса MR ==="
      
      # Делаем API-запрос и сразу парсим ответ через Python
      APPROVED=$(curl -s --header "PRIVATE-TOKEN: $API_TOKEN" \
        "$CI_API_V4_URL/projects/$CI_PROJECT_ID/merge_requests/$CI_MERGE_REQUEST_IID" | \
        python3 -c "import json, sys; print(json.load(sys.stdin)['approved'])")
      
      echo "Статус апрува: $APPROVED"
      
      if [ "$APPROVED" = "True" ]; then
        echo "✅ MR одобрен! Триггерим Jenkins..."
        # Ваш curl на Jenkins (пример):
        curl -X POST "${JENKINS_URL}/generic-webhook-trigger/invoke?token=MR_APPROVED_TOKEN" \
          -H "Content-Type: application/json" \
          -d '{"mr_id": "'"${CI_MERGE_REQUEST_IID}"'"}'
      else
        echo "❌ MR не одобрен. Выход."
        exit 1
      fi
