stages:
  - trigger

trigger_jenkins:
  stage: trigger
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'  # Срабатывает при любом пуше в main (включая мерж MR)
  script:
    - |
      curl -X POST "${JENKINS_URL}/generic-webhook-trigger/invoke?token=REPO_CLONE_TOKEN" \
        -H "Content-Type: application/json" \
        -d '{"repo_url":"'"${CI_REPOSITORY_URL}"'"}'
      echo "✅ Jenkins triggered for ${CI_REPOSITORY_URL}"
