stages:
  - test

# Эта job будет запускаться при любом изменении MR
mr_listener:
  stage: test
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  script:
    - echo "MR ID: $CI_MERGE_REQUEST_IID"
    - echo "Source branch: $CI_MERGE_REQUEST_SOURCE_BRANCH"
    - echo "Target branch: $CI_MERGE_REQUEST_TARGET_BRANCH"
    - echo "Approved: $CI_MERGE_REQUEST_APPROVED"  # Будет 'true' после апрува
