stages:
  - trigger_jenkins

trigger_jenkins_on_approved_mr:
  stage: trigger_jenkins
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" &&
            $CI_MERGE_REQUEST_TARGET_BRANCH == "main" &&
            $CI_MERGE_REQUEST_SOURCE_BRANCH == "dev" &&
            $CI_MERGE_REQUEST_APPROVED == "true"'
  script:
    - |
      echo "Triggering Jenkins for APPROVED MR !${CI_MERGE_REQUEST_IID}"
      curl -X POST \
        "${JENKINS_URL}/generic-webhook-trigger/invoke?token=MR_APPROVED_TOKEN" \
        -H "Content-Type: application/json" \
        -d '{
          "merge_request": {
            "id": "${CI_MERGE_REQUEST_IID}",
            "source_branch": "dev",
            "target_branch": "main",
            "status": "approved",
            "web_url": "${CI_MERGE_REQUEST_PROJECT_URL}/-/merge_requests/${CI_MERGE_REQUEST_IID}"
          },
          "project": {
            "name": "${CI_PROJECT_NAME}",
            "url": "${CI_PROJECT_URL}"
          }
        }'
