stages:
  - test

print_on_approval:
  stage: test
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && 
           $CI_MERGE_REQUEST_TARGET_BRANCH == "main"'
  before_script:
    - apt-get update -qq && apt-get install -y -qq jq curl
  script:
    - |
      echo "=== Начало проверки MR ==="
      echo "ID MR: $CI_MERGE_REQUEST_IID"
      echo "Source branch: $CI_MERGE_REQUEST_SOURCE_BRANCH"
      echo "Target branch: $CI_MERGE_REQUEST_TARGET_BRANCH"

      # Проверка апрува через API
      API_RESPONSE=$(curl -s --header "PRIVATE-TOKEN: $API_TOKEN" \
        "$CI_API_V4_URL/projects/$CI_PROJECT_ID/merge_requests/$CI_MERGE_REQUEST_IID")
      
      APPROVED=$(echo "$API_RESPONSE" | jq -r '.approved')
      echo "Статус апрува: $APPROVED"

      if [ "$APPROVED" = "true" ]; then
        echo "✅ MR получил апрув! Можно запускать Jenkins"
      else
        echo "❌ MR еще не апрувнут. Пропускаем триггер Jenkins"
      fi
