stages:
  - check

check_approval:
  stage: check
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && 
           $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'
  script:
    - |
      echo "=== Проверка статуса MR ==="
      
      # GitLab предоставляет встроенный curl и базовые инструменты
      API_RESPONSE=$(curl -s --header "PRIVATE-TOKEN: $API_TOKEN" \
        "$CI_API_V4_URL/projects/$CI_PROJECT_ID/merge_requests/$CI_MERGE_REQUEST_IID")
      
      # Используем встроенный Python для парсинга JSON (не требует jq)
      APPROVED=$(python3 -c "import json, os; print(json.loads(os.environ['API_RESPONSE']).get('approved', False))")
      
      echo "Статус апрува: $APPROVED"
      if [ "$APPROVED" = "True" ]; then
        echo "✅ MR одобрен! Триггерим Jenkins..."
        # Ваш curl на Jenkins
      else
        echo "❌ MR не одобрен. Выход."
        exit 1
      fi
