stages:
  - build   # Обязательно объявляем stage перед использованием

build:
  stage: build   # Явно указываем принадлежность к stage
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'
      when: always
    - when: never
  script:
    - echo "Сборка для MR в main"
