
stages:
  - trigger_jenkins

# Задача, которая запускает Jenkins только после апрува MR
trigger_jenkins_on_approved_mr:
  stage: trigger_jenkins
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'  # Только для MR
      if: '$CI_MERGE_REQUEST_APPROVED == "true"'          # Только если MR апрувнут
  script:
    - |
      echo "Triggering Jenkins for APPROVED MR !${CI_MERGE_REQUEST_IID}"
      curl -X POST \
        "${JENKINS_URL}/generic-webhook-trigger/invoke?token=MR_APPROVED_TOKEN" \
        -H "Content-Type: application/json" \
        -d '{
          "merge_request": {
            "id": "${CI_MERGE_REQUEST_IID}",
            "source_branch": "${CI_MERGE_REQUEST_SOURCE_BRANCH}",
            "target_branch": "${CI_MERGE_REQUEST_TARGET_BRANCH}",
            "status": "approved",
            "web_url": "${CI_MERGE_REQUEST_PROJECT_URL}/-/merge_requests/${CI_MERGE_REQUEST_IID}"
          },
          "project": {
            "name": "${CI_PROJECT_NAME}",
            "url": "${CI_PROJECT_URL}"
          }
        }'
