apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8srestrictedresources
spec:
  crd:
    spec:
      names:
        kind: K8sRestrictedResources
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8srestrictedresources

        # Общие условия для всех мутаций
        is_restricted_ns(ns_name) {
          data.inventory.namespace[ns_name].metadata.labels["operations.gatekeeper.policy.dev"] == "restricted"
        }

        needs_cpu_limit(resources) {
          not resources.limits
        } else {
          resources.limits.cpu != "50m"
        }

        needs_mem_limit(resources) {
          not resources.limits
        } else {
          resources.limits.memory != "50Mi"
        }

        needs_cpu_request(resources) {
          not resources.requests
        } else {
          resources.requests.cpu != "50m"
        }

        needs_mem_request(resources) {
          not resources.requests
        } else {
          resources.requests.memory != "50Mi"
        }

        # Генерация операций мутации
        make_operations(container) = ops {
          resources := object.get(container, "resources", {})
          ops := [
            op |
            # Операции для limits
            needs_cpu_limit(resources);
            op := {"operation": "add", "path": "/spec/containers/0/resources/limits/cpu", "value": "50m"}
          ] + [
            op |
            needs_mem_limit(resources);
            op := {"operation": "add", "path": "/spec/containers/0/resources/limits/memory", "value": "50Mi"}
          ] + [
            op |
            # Операции для requests
            needs_cpu_request(resources);
            op := {"operation": "add", "path": "/spec/containers/0/resources/requests/cpu", "value": "50m"}
          ] + [
            op |
            needs_mem_request(resources);
            op := {"operation": "add", "path": "/spec/containers/0/resources/requests/memory", "value": "50Mi"}
          ]
        }

        mutation := {
          "apiVersion": "v1",
          "kind": "Pod",
          "operations": make_operations(input.review.object.spec.containers[0])
        } if {
          input.review.object.kind == "Pod"
          input.review.object.metadata.namespace == ns_name
          is_restricted_ns(ns_name)
          count(make_operations(input.review.object.spec.containers[0])) > 0
        }
